### ISSUE TITLE
Upgrade JSONSchema.jl version to v1.0.1

### ISSUE THREAD

**Issue by ndortega** [GenieFramework/SwaggerMarkdown.jl#6]
JSONSchema.jl recently upgraded their HTTP.jl dependency to support the recent 1.0.0 release. I'd also like to upgrade my package to use the latest version without breaking the integration between [Oxygen.jl](https://github.com/ndortega/Oxygen.jl) and SwaggerMarkdown.jl

Here's the latest release:
https://github.com/fredo-dedup/JSONSchema.jl/releases/tag/v1.0.1

**Comment by jiachengzhang1** [comment]
@ndortega I'll look at the upgrade. Oxygen.jl looks great, glad you include the SwaggerMarkdown 🙏😁, checkout [SwagUI.jl](https://github.com/GenieFramework/SwagUI.jl), it takes a step further to generate the swagger ui page

**Comment by jiachengzhang1** [comment]
@ndortega updated, let me know how it goes

**Comment by ndortega** [comment]
@jiachengzhang1 Thanks! Everything looks good in the Project.toml file. I'll raise another issue if I run into any issues from my end.
